#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1569894280                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             : https://apps.apple.com/us/app/tsk-notify/id1569894280 # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : https://apps.apple.com/us/app/tsk-notify/id1569894280                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : #assets/screenshots/IMG_9476.PNG                    # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Taking L’s? For less than a cup of coffee a month, TSK Notify is the most affordable and comprehensive option to keep you in the loop for all things sneakers!

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Torin Turner                               
your_link                                 : https://8squaredplus5.com                     
your_city                                 : Cyberspace                                
email_address                             : support@tsknotify.app
facebook_username                         :                                           
instagram_username                        : sneakerknockerzllc
twitter_username                          : 
github_username                           :
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : THE LATEST SNEAKER NEWS
    description                           : TSK Notify has you covered when it comes to unreleased kicks. With our insider information we gather we are determined to ensure you have the most up-to-date information nearly as soon as we receive it ourselves!
    fontawesome_icon_name                 : magic
    
  - title                                 : COMPREHENSIVE RELEASE GUIDES
    description                           : Our team over here at TSK Notify is working 24/7 to make sure YOU know which shoes will make you the most profit! Providing resell predictions, whether to cop or not, sell or hold, and retail websites where these shoes can be purchased!
    fontawesome_icon_name                 : mobile

  - title                                 : REAL-TIME SNEAKER RAFFLES
    description                           : Our state of the art raffle monitors are connected to provide you with instant posts containing raffle times and links to enter! We only cover the HYPEST of sneakers too, so don’t worry about any other products from any of their respective stores.
    fontawesome_icon_name                 : play-circle

  - title                                 : RAFFLE ENTRY TRACKING
    description                           : No more forgetting! See which sneakers you’ve entered by tapping the checkmark and viewing on your profile tab an overall view of all sneakers you have ever entered raffles for!
    fontawesome_icon_name                 : sync

  - title                                 : RELEASE CALENDAR
    description                           : Read up on our detailed descriptions, images, and in-depth sneaker information. Not to mention our iOS Calendar app implementation as well as our personalized notifications, just a tap away.
    fontawesome_icon_name                 : adjust
  
  - title                                 : REAL TIME, PERSONALIZED NOTIFICATIONS
    description                           : How quick are you? Live notifications sent by the professionals here at TSK Notify send out notifications for the HYPEST of posts just hitting the app. Also, utilizing our notification bell button on any sneaker, you will be notified on that release date prior to launch to check TSK Notify for the most up-to-date information to score your pair!
    fontawesome_icon_name                 : star

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : gradient.jpg                # Replace with alternative image path or image URL.
cover_overlay_color                       : "#000000"
cover_overlay_transparency                : 0.0

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
